### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by yhzhan1002** [JrDong/Android-Material-Sloth#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.StackOverflowError
                      at android.view.Choreographer.access$500(Choreographer.java:69)
                      at android.view.Choreographer$CallbackQueue.addCallbackLocked(Choreographer.java:782)
                      at android.view.Choreographer.postCallbackDelayedInternal(Choreographer.java:313)
                      at android.view.Choreographer.postCallbackDelayed(Choreographer.java:299)
                      at android.view.Choreographer.postCallback(Choreographer.java:273)
                      at android.view.ViewRootImpl.scheduleConsumeBatchedInput(ViewRootImpl.java:5518)
                      at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:985)
                      at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:915)
                      at android.view.ViewGroup.invalidateChildFast(ViewGroup.java:4374)
                      at android.view.View.invalidateViewProperty(View.java:10576)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationUpdate(ViewPropertyAnimator.java:1030)
                      at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1179)
                      at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1115)
                      at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1144)
                      at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:510)
                      at android.animation.ValueAnimator.start(ValueAnimator.java:921)
                      at android.animation.ValueAnimator.start(ValueAnimator.java:931)
                      at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:772)
                      at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:355)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.hide(BottomScrollBehavior.java:83)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.access$100(BottomScrollBehavior.java:17)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior$2.onAnimationCancel(BottomScrollBehavior.java:103)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
                      at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
                      at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
                      at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
                      at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.hide(BottomScrollBehavior.java:60)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.access$100(BottomScrollBehavior.java:17)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior$2.onAnimationCancel(BottomScrollBehavior.java:103)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
                      at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
                      at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
                      at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
                      at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.hide(BottomScrollBehavior.java:60)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.access$100(BottomScrollBehavior.java:17)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior$2.onAnimationCancel(BottomScrollBehavior.java:103)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
                      at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
                      at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
                      at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
                      at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.hide(BottomScrollBehavior.java:60)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior.access$100(BottomScrollBehavior.java:17)
                      at xyz.ibat.sloth.view.behavior.BottomScrollBehavior$2.onAnimationCancel(BottomScrollBehavior.java:103)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
                  	at an

**Comment by yhzhan1002** [comment]
列表缓慢滑动的时候出现
